name: Build the project Debug Sandbox on Windows
run-name: ${{ github.actor }} Is building the Sandbox
on: [pull_request]
jobs:
  build-the-sandbox:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify LLVM
        shell: pwsh
        run: |
          clang++ --version

      - name: Install Make
        shell: pwsh
        run: |
          choco install make -y

      - name: Verify Make
        shell: pwsh
        run: |
          make --version
      - name: Check compiler
        shell: pwsh
        run: |
          clang++ --version
          where clang++
          where gcc
          where g++
          echo "CC=$env:CC"
          echo "CXX=$env:CXX"

      - name: Install Premake
        shell: pwsh
        run: |
          $version = "5.0.0-beta4"
          $url = "https://github.com/premake/premake-core/releases/download/v5.0.0-beta8/premake-5.0.0-beta8-windows.zip"

          Invoke-WebRequest $url -OutFile premake.zip
          Expand-Archive premake.zip -DestinationPath "$env:RUNNER_TEMP\premake"

          "$env:RUNNER_TEMP\premake" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Generate makefiles
        shell: pwsh
        run: |
          .\build.ps1 gen

      - name: Build the project
        shell: pwsh
        run: |
          .\build.ps1 build DEBUG

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Sandbox
          path: bin
